language: ruby

cache:
  bundler: true
  npm: true

rvm:
  - 2.6.3

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
  chrome: stable

before_install:
  - nvm install 10
  - npm install -g @lhci/cli@0.3.x zero

install:
  - bundle install

before_script:
  - pwd
  - mkdir -p _site
  - cd _site
  - zero &
  - cd $TRAVIS_BUILD_DIR
  - pwd

script:
  - jekyll build

notifications:
  email: false

after_success:
  - lhci autorun
