# Permalinks
permalink: /:title.html

# Setup
title:          j0k3r.net
paginate:       10

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jérémy Benoist
  url:          https://www.j0k3r.net

future: false

exclude:
  - vendor
  - deploy.sh
  - Gemfile*
  - README.md
  - Rakefile
